"use client";

import { Settings2, ShieldCheck, Sparkles, Gauge, ArrowRight } from "lucide-react";
import type { ToolDefinition, ToolId } from "@/lib/tools";
import type { ToolOptions } from "@/components/image-tools/types";

type SettingsCardProps = {
  activeTool: ToolId;
  tool: ToolDefinition;
  options: ToolOptions;
  error: string;
  busy: boolean;
  title: string;
  onOption: (key: string, value: string) => void;
  onToggle: (key: string) => void;
  onReset: () => void;
  onRun: () => void;
};

export function SettingsCard({ activeTool, tool, options, error, busy, title, onOption, onToggle, onReset, onRun }: SettingsCardProps) {
  return (
    <section className="settings-card">
      <div className="card-heading"><div><Settings2 size={20} /><h2>{activeTool === "compress" ? "Compression Settings" : `${title} Settings`}</h2></div><button className="reset-button" onClick={onReset}>↻ Reset</button></div>
      <div className="settings-grid">
        {activeTool === "compress" && <><label className="setting-field">Output format<select value={options.format} onChange={(event) => onOption("format", event.target.value)}><option value="auto">Auto</option><option value="jpeg">JPG</option><option value="png">PNG</option><option value="webp">WebP</option><option value="avif">AVIF</option></select></label><label className="setting-field range-field">Compression level <output>{options.quality}%</output><input type="range" min="20" max="100" value={options.quality} onChange={(event) => onOption("quality", event.target.value)} /><small><span>Smaller size</span><span>Balanced</span><span>Higher quality</span></small></label><button className={`check-option ${options.format === "auto" ? "checked" : ""}`} onClick={() => onOption("format", options.format === "auto" ? "webp" : "auto")}><span>✓</span> Keep original format when possible</button></>}
        {activeTool === "convert" && <><div className="setting-field format-picker"><span>Output format</span><div className="format-options">{[["jpeg", "JPG"], ["png", "PNG"], ["webp", "WebP"], ["avif", "AVIF"]].map(([value, label]) => <button key={value} className={options.format === value ? "selected" : ""} onClick={() => onOption("format", value)}>{label}</button>)}</div></div><label className="setting-field range-field">Quality <output>{options.quality}%</output><input type="range" min="20" max="100" value={options.quality} onChange={(event) => onOption("quality", event.target.value)} /></label></>}
        {activeTool === "resize" && <><div className="segmented setting-field"><button className={options.resizeMode === "pixels" ? "selected" : ""} onClick={() => onOption("resizeMode", "pixels")}>Pixels</button><button className={options.resizeMode === "percentage" ? "selected" : ""} onClick={() => onOption("resizeMode", "percentage")}>Percentage</button><button className={options.resizeMode === "preset" ? "selected" : ""} onClick={() => onOption("resizeMode", "preset")}>Preset</button></div>{options.resizeMode === "percentage" ? <label className="setting-field">Scale (%)<input inputMode="numeric" value={options.percentage ?? "100"} onChange={(event) => onOption("percentage", event.target.value)} /></label> : <><label className="setting-field">Width (px)<input inputMode="numeric" value={options.width} onChange={(event) => onOption("width", event.target.value)} /></label><label className="setting-field">Height (px)<input inputMode="numeric" placeholder="Keep ratio" value={options.height} onChange={(event) => onOption("height", event.target.value)} /></label></>}{options.resizeMode === "preset" && <label className="setting-field">Common preset<select value={options.preset} onChange={(event) => onOption("preset", event.target.value)}><option value="social">Social Media 1080 × 1080</option><option value="story">Story 1080 × 1920</option><option value="thumbnail">Thumbnail 1280 × 720</option></select></label>}<button className={`check-option ${options.preventEnlargement === "true" ? "checked" : ""}`} onClick={() => onToggle("preventEnlargement")}><span>✓</span> Prevent enlargement</button></>}
        {activeTool === "crop" && <><label className="setting-field">Aspect ratio<select value={options.ratio} onChange={(event) => onOption("ratio", event.target.value)}><option value="free">Free</option><option value="square">1:1 Square</option><option value="landscape">16:9 Landscape</option><option value="portrait">4:5 Portrait</option></select></label>{["left", "top", "width", "height"].map((key) => <label className="setting-field" key={key}>{key[0].toUpperCase() + key.slice(1)} (px)<input inputMode="numeric" value={options[key] ?? ""} onChange={(event) => onOption(key, event.target.value)} /></label>)}</>}
        {activeTool === "rotate" && <><div className="quick-actions"><button onClick={() => onOption("angle", "270")}>↶ Rotate Left 90°</button><button onClick={() => onOption("angle", "90")}>↷ Rotate Right 90°</button><button onClick={() => onOption("angle", "180")}>⟳ Rotate 180°</button></div><label className="setting-field">Output format<select value={options.format} onChange={(event) => onOption("format", event.target.value)}><option value="auto">Keep original format</option><option value="jpeg">JPG</option><option value="png">PNG</option><option value="webp">WebP</option></select></label></>}
        {activeTool === "flip" && <div className="quick-actions"><button className={options.direction === "horizontal" ? "selected" : ""} onClick={() => onOption("direction", "horizontal")}>⇆ Flip Horizontal</button><button className={options.direction === "vertical" ? "selected" : ""} onClick={() => onOption("direction", "vertical")}>⇅ Flip Vertical</button></div>}
        {(activeTool === "ocr" || activeTool === "screenshot-to-text") && <><label className="setting-field">OCR language<select value={options.language} onChange={(event) => onOption("language", event.target.value)}><option value="eng">English (default)</option><option value="deu">German</option><option value="fra">French</option><option value="hin">Hindi</option><option value="spa">Spanish</option></select></label><label className="setting-field">Layout mode<select value={options.psm} onChange={(event) => onOption("psm", event.target.value)}><option value="6">Standard block</option><option value="11">Sparse / screenshot</option></select></label><button className={`check-option ${options.enhance === "true" ? "checked" : ""}`} onClick={() => onToggle("enhance")}><span>✓</span> Enhance image for better accuracy</button></>}
        {activeTool === "upscale" && <><div className="segmented setting-field"><button className="selected">2×</button><button disabled>4×</button><button disabled>8×</button></div><button className={`check-option ${options.enhance === "true" ? "checked" : ""}`} onClick={() => onToggle("enhance")}><span>✓</span> Enhance details</button></>}
        {activeTool === "image-to-pdf" && <><label className="setting-field">Page size<select value={options.pageSize} onChange={(event) => onOption("pageSize", event.target.value)}><option value="a4">A4</option><option value="letter">Letter</option><option value="original">Original image</option></select></label><label className="setting-field">Orientation<select value={options.orientation} onChange={(event) => onOption("orientation", event.target.value)}><option value="portrait">Portrait</option><option value="landscape">Landscape</option></select></label><label className="setting-field">Margin<select value={options.margin} onChange={(event) => onOption("margin", event.target.value)}><option value="small">Small</option><option value="none">None</option></select></label></>}
        {activeTool === "screenshot-to-pdf" && <><label className="setting-field">Page size<select value={options.pageSize} onChange={(event) => onOption("pageSize", event.target.value)}><option value="original">Original screenshot</option><option value="a4">A4</option><option value="letter">Letter</option></select></label><div className="setting-note"><ShieldCheck size={18} /><span>Screenshot pixels are preserved; no cursor is added.</span></div></>}
        {activeTool === "strip-metadata" && <div className="check-list"><strong>Metadata that will be removed</strong><span>✓ EXIF data (camera info)</span><span>✓ GPS location data</span><span>✓ Device information</span><span>✓ Software information</span></div>}
        {activeTool === "remove-background" && <div className="setting-note"><ShieldCheck size={18} /><span>A local U²-Net model creates a transparent PNG cutout.</span></div>}
        {activeTool === "image-to-base64" && <label className="setting-field">Output mode<select value={options.base64Mode} onChange={(event) => onOption("base64Mode", event.target.value)}><option value="data-uri">Data URI</option><option value="raw">Raw Base64</option></select></label>}
        {activeTool === "base64-to-image" && <div className="setting-note"><ShieldCheck size={18} /><span>Decode a data URI or raw Base64 payload into a PNG preview.</span></div>}
        {activeTool === "upscale" && <div className="setting-note"><ShieldCheck size={18} /><span>A local FSRCNN model produces a 2× PNG with no paid API.</span></div>}
      </div>
      {error && <div className="error-banner" role="alert">{error}</div>}
      <button className="run-button" onClick={onRun} disabled={busy}>{busy ? <><Gauge size={18} className="spin" /> Processing…</> : <><Sparkles size={18} /> {title === "Image Compressor" ? "Compress Images" : `Run ${title}`} <ArrowRight size={18} /></>}</button>
    </section>
  );
}
